name: Package and build release versions

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取分支
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: 创建包
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: 上传到 Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: NDui_Plus
          path: .release/*.zip