name: Package and build release versions

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'


jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -p 389434